/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  public enum Dns: String {

    /**
     The list of IPv4 or IPv6 addresses resolved during DNS lookup.

      - Examples:
      ```
      attributes[SemanticConventions.Dns.answers.rawValue] = ["10.0.0.1", "2001:0db8:85a3:0000:0000:8a2e:0370:7334"]
      ```

     - Requires: Value type should be `[String]`
    */
    case answers = "dns.answers"

    /**
     The name being queried.

      - Examples:
      ```
      attributes[SemanticConventions.Dns.questionName.rawValue] = "www.example.com"
      attributes[SemanticConventions.Dns.questionName.rawValue] = "opentelemetry.io"
      ```

     - Note: If the name field contains non-printable characters (below 32 or above 126), those characters should be represented as escaped base 10 integers (\DDD). Back slashes and quotes should be escaped. Tabs, carriage returns, and line feeds should be converted to \t, \r, and \n respectively.

     - Requires: Value type should be `String`
    */
    case questionName = "dns.question.name"
  }
}