name: Release

permissions:
  contents: write  # Required for creating GitHub Releases and uploading artifacts

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: opentelemetry-swift-packages

      - name: Extract Version from Tag
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Build XCFramework
        working-directory: ./opentelemetry-swift-packages
        run: |
          make xcframework

      - name: Upload OpenTelemetryApi.zip
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: OpenTelemetryApi
          path: ./opentelemetry-swift-packages/artifacts/OpenTelemetryApi.zip
          if-no-files-found: error

      - name: Upload version_info.md
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: OpenTelemetryApi-VersionInfo
          path: ./opentelemetry-swift-packages/artifacts/version_info.md
          if-no-files-found: error

      - name: Publish GH Asset
        working-directory: ./opentelemetry-swift-packages
        run: |
          make publish-github VERSION=${VERSION}
